// src/components/btn-go-to-contact/btn-go-to-contact.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-btn-go-to-contact',
  templateUrl: './btn-go-to-contact.component.html',
  styleUrls: ['./btn-go-to-contact.component.scss']
})
export class BtnGoToContactComponent {

}

<div class="grid grid-cols-12 gap-4">
  <div class="col-start-3 col-end-11 flex justify-center items-center">
    <a href="#contact"
      class="bg-white px-4 py-1 cursor-pointer rounded-lg hover:bg-secondary  hover:text-white xl:text-2xl xl:px-6 xl:py-2">Contact
      me!</a>
  </div>
</div>

// src/components/btn_go_to_contact.vue
<script setup>
</script>

<template>
  <div class="grid grid-cols-12 gap-4">
  <div class="col-start-3 col-end-11 flex justify-center items-center">
    <a href="#contact"
      class="bg-white px-4 py-1 cursor-pointer rounded-lg hover:bg-secondary  hover:text-white xl:text-2xl xl:px-6 xl:py-2">Contact
      me!</a>
  </div>
</div>
</template>

<style scoped></style>
