// src/components/contact-text/contact-text.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-contact-text',
  templateUrl: './contact-text.component.html',
  styleUrls: ['./contact-text.component.scss']
})
export class ContactTextComponent {

}

<div class="col-span-full grid grid-cols-12 gap-y-8 gap-x-1">

  <div class="text-white col-start-1 col-end-11 text-4xl text-right font-bold xl:text-5xl">
    Contact
  </div>
  <div class="col-start-11 col-end-12 flex items-center">
    <div class="h-1 w-full bg-secondary rounded-xl"></div>
  </div>
  <div class="col-start-1 col-end-2 flex items-center">
    <div class="h-1 w-full bg-secondary rounded-xl"></div>
  </div>
  <div class="text-white col-start-2 col-end-12 text-xl font-bold xl:text-2xl">Got a problem to solve?</div>
  <div class="text-white col-start-2 col-end-12 text-xs xl:text-base">Contact me through this form, I am
    interested in hearing you, knowing your ideas and contributing to your projects with my work.</div>
  <div class="text-white col-start-2 col-end-12 text-xs flex xl:text-base">
    <div class="text-white xl:text-base"> Need a Frontend developer?</div>
    <div class="ml-4 text-white font-bold xl:text-base">Contact me!</div>
  </div>
</div>

// src/components/contact_text.vue
<script setup>
</script>

<template>
  <div class="col-span-full grid grid-cols-12 gap-y-8 gap-x-1">

  <div class="text-white col-start-1 col-end-11 text-4xl text-right font-bold xl:text-5xl">
    Contact
  </div>
  <div class="col-start-11 col-end-12 flex items-center">
    <div class="h-1 w-full bg-secondary rounded-xl"></div>
  </div>
  <div class="col-start-1 col-end-2 flex items-center">
    <div class="h-1 w-full bg-secondary rounded-xl"></div>
  </div>
  <div class="text-white col-start-2 col-end-12 text-xl font-bold xl:text-2xl">Got a problem to solve?</div>
  <div class="text-white col-start-2 col-end-12 text-xs xl:text-base">Contact me through this form, I am
    interested in hearing you, knowing your ideas and contributing to your projects with my work.</div>
  <div class="text-white col-start-2 col-end-12 text-xs flex xl:text-base">
    <div class="text-white xl:text-base"> Need a Frontend developer?</div>
    <div class="ml-4 text-white font-bold xl:text-base">Contact me!</div>
  </div>
</div>
</template>

<style scoped></style>
