// src/components/greeting/greeting.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-greeting',
  templateUrl: './greeting.component.html',
  styleUrls: ['./greeting.component.scss']
})
export class GreetingComponent {

  
}

<div class="grid grid-cols-12 text-white text-center gap-y-6 mb-8">
  <div class="col-start-1 col-end-13 flex justify-center">
    <div class="flex flex-col-reverse justify-between">
      <div class="w-full flex justify-start items-end text-3xl writingMode-b-rl rotate-180 mb-2">I</div>
      <div class="w-full flex justify-end items-end text-3xl writingMode-b-rl rotate-180 mt-1">am</div>
    </div>
    <div>
      <div class="text-3xl font-bold flex justify-between">
        <div class="">Dennis</div>
        <div class="">Georg</div>
        <div class="">Ertel</div>
      </div>
      <div class="text-2xsl xl:text-2xl flex justify-between text-secondary">
        <div>FULL STACK&nbsp;</div>
        <div>DEVELOPER</div>
      </div>
    </div>
  </div>
  <div class="row-start-3 row-span-2 col-start-3 col-end-11 flex justify-center items-center">
    <a href="#contact" class="bg-white text-black px-4 py-1 cursor-pointer rounded-lg hover:bg-secondary">Contact
      me!</a>
  </div>

</div>

// src/components/greeting.vue
<script setup></script>

<template>
   <div class="grid grid-cols-12 text-white text-center gap-y-6 mb-8">
      <div class="col-start-1 col-end-13 flex justify-center">
         <div class="flex flex-col-reverse justify-between">
            <div class="w-full flex justify-start items-end text-3xl writingMode-b-rl rotate-180 mb-2">I</div>
            <div class="w-full flex justify-end items-end text-3xl writingMode-b-rl rotate-180 mt-1">am</div>
         </div>
         <div>
            <div class="text-3xl font-bold flex justify-between">
               <div class="">Dennis</div>
               <div class="">Georg</div>
               <div class="">Ertel</div>
            </div>
            <div class="text-2xsl xl:text-2xl flex justify-between text-secondary">
               <div>FULL STACK&nbsp;</div>
               <div>DEVELOPER</div>
            </div>
         </div>
      </div>
      <div class="row-start-3 row-span-2 col-start-3 col-end-11 flex justify-center items-center">
         <a href="#contact" class="bg-white text-black px-4 py-1 cursor-pointer rounded-lg hover:bg-secondary">Contact me!</a>
      </div>
   </div>
</template>

<style scoped></style>
