// src/components/my-skills/my-skills.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-my-skills',
  templateUrl: './my-skills.component.html',
  styleUrls: ['./my-skills.component.scss'],
})
export class MySkillsComponent {
  textMySkills =
    'I have grown my frontend development skills that have allowed me to crate different real projects.';
}

<div class="col-span-full grid grid-cols-12 gap-6 text-white">
  <div class="col-start-2 col-end-11 flex justify-end items-center text-4xl font-bold md:col-end-10 xl:text-5xl">My
    skills</div>
  <div class="col-start-11 col-end-13 flex items-center md:col-start-10 xl:col-end-12">
    <div class="h-1 w-full bg-secondary rounded-xl"></div>
  </div>
  <div class="col-start-2 col-end-12 gap-12 text-end xl:text-center">{{ textMySkills }}</div>
</div>

// src/components/my_skills.vue
<script setup>
const textMySkills = "I have grown my frontend development skills that have allowed me to crate different real projects.";
</script>

<template>
   <div class="col-span-full grid grid-cols-12 gap-6 text-white">
      <div class="col-start-2 col-end-11 flex justify-end items-center text-4xl font-bold md:col-end-10 xl:text-5xl">My skills</div>
      <div class="col-start-11 col-end-13 flex items-center md:col-start-10 xl:col-end-12">
         <div class="h-1 w-full bg-secondary rounded-xl"></div>
      </div>
      <div class="col-start-2 col-end-12 gap-12 text-end xl:text-center">{{ textMySkills }}</div>
   </div>
</template>

<style scoped></style>
