// src/components/scroll-up-section/scroll-up-section.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-scroll-up-section',
  templateUrl: './scroll-up-section.component.html',
  styleUrls: ['./scroll-up-section.component.scss']
})
export class ScrollUpSectionComponent {

}

<div class="col-span-full grid grid-cols-12 gap-x-1 mt-4">
  <div class="col-start-2 col-end-12 grid grid-cols-12">
    <div class="col-start-11 col-end-13 lg:col-start-12">
      <a href="#top">
        <svg id="Icons" style="enable-background:new 0 0 32 32;" version="1.1" viewBox="0 0 32 32" xml:space="preserve"
          class="stroke-white hover:stroke-secondary cursor-pointer" xmlns="http://www.w3.org/2000/svg"
          xmlns:xlink="http://www.w3.org/1999/xlink">
          <style type="text/css">
            .st0 {
              fill: none;
              stroke-width: 2;
              stroke-linecap: round;
              stroke-linejoin: round;
              stroke-miterlimit: 10;
            }
          </style>
          <circle class="st0" cx="16" cy="16" r="13" />
          <line class="st0" x1="16" x2="16" y1="23" y2="10" />
          <polyline class="st0" points="12,14 16,10 20,14 " />
        </svg>
      </a>
    </div>
  </div>
</div>

// src/components/scroll_up_section.vue
<script setup>
</script>

<template>
  <div class="col-span-full grid grid-cols-12 gap-x-1 mt-4">
    <div class="col-start-2 col-end-12 grid grid-cols-12">
      <div class="col-start-11 col-end-13 lg:col-start-12">
        <a href="#top">
          <svg id="Icons" style="enable-background:new 0 0 32 32;" version="1.1" viewBox="0 0 32 32" xml:space="preserve"
            class="stroke-white hover:stroke-secondary cursor-pointer" xmlns="http://www.w3.org/2000/svg"
            xmlns:xlink="http://www.w3.org/1999/xlink">
            <circle class="st0" cx="16" cy="16" r="13" />
            <line class="st0" x1="16" x2="16" y1="23" y2="10" />
            <polyline class="st0" points="12,14 16,10 20,14 " />
          </svg>
        </a>
      </div>
    </div>
  </div>
</template>

<style scoped>
.st0 {
  fill: none;
  stroke-width: 2;
  stroke-linecap: round;
  stroke-linejoin: round;
  stroke-miterlimit: 10;
}
</style>
